In [2]:
#1)numpy version
import numpy as np
a=numpy.array([1,5,3,8,7])
np.__version__

'1.16.5'

In [4]:
#2)to get help on add function
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [10]:
#3)testing none of the elements of a given array is zero:
a=np.array([1,5,3,8,7])
print("Original array:")
print(a)
print("Test of one of the elements of the  array is zero: ",np.all(a))
x=np.array([0,2,3,4,3])
print(x)
print("Test of one of the elements of the  array is zero: ",np.all(x))

Original array:
[1 5 3 8 7]
Test of one of the elements of the  array is zero:  True
[0 2 3 4 3]
Test of one of the elements of the  array is zero:  False


In [12]:
#4)testing any of the elements of a given array is non-zero then its :
a=np.array([0,0,0,0,0])
print("Original array:")
print(a)
print("Test of one of the elements of the  array is non-zero: ",np.any(a))
x=np.array([0,0,1,0,0])
print(x)
print("Test of one of the elements of the  array is non-zero: ",np.any(x))

Original array:
[0 0 0 0 0]
Test of one of the elements of the  array is non-zero:  False
[0 0 1 0 0]
Test of one of the elements of the  array is non-zero:  True


In [16]:
#5)Testing the element-wise for finiteness
a=np.array([0,1,np.nan,np.inf])
print("Original array:")
print(a)
print("Testing the element-wise for finiteness:",np.isfinite(a))

Original array:
[ 0.  1. nan inf]
Testing the element-wise for finiteness: [ True  True False False]


In [17]:
#6)Testing the element-wise for positive or negative infinity
a=np.array([0,1,np.nan,np.inf])
print("Original array:")
print(a)
print("Testing the element-wise for positive or negative infinity:",np.isinf(a))

Original array:
[ 0.  1. nan inf]
Testing the element-wise for positive or negative infinity: [False False False  True]


In [18]:
#7)Test element-wise for NaN of a given array
a=np.array([0,1,np.nan,np.inf])
print("Original array:")
print(a)
print("Test element-wise for NaN of a given array:",np.isnan(a))

Original array:
[ 0.  1. nan inf]
Test element-wise for NaN of a given array: [False False  True False]


In [20]:
#8)Test element-wise for complex ,real number of a given array
#Also test for a given number is scalar or not
a=np.array([1+1j,1+0j,4.5,3,2j])
print("Original array:",a)
print("Checking for complex number:",np.iscomplex(a))
print("Checking for real number:",np.isreal(a))
print("Checking for scalar number:",np.isscalar(a))

Original array: [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 0. +2.j]
Checking for complex number: [ True False False False  True]
Checking for real number: [False  True  True  True False]
Checking for scalar number: False


In [22]:
#9)Test whether two arrays are element-wise equal within a tolerance
print("Test whether two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7],[1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8],[1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8],[1.0001e10,1e-9]))
print(np.allclose([1.0,np.nan],[1.0,np.nan]))
print(np.allclose([1.0,np.nan],[1.0,np.nan],equal_nan=True))

Test whether two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [23]:
#10)Element wise comparison
x=np.array([2,5,7])
y=np.array([5,2,7])
print("Original Numbers:")
print(x)
print(y)
print("Comparison-greater:",np.greater(x,y))
print("Comparison-greater_equal:",np.greater_equal(x,y))
print("Comparison-less:",np.less(x,y))
print("Comparison-less_equal:",np.less_equal(x,y))

Original Numbers:
[2 5 7]
[5 2 7]
Comparison-greater: [False  True False]
Comparison-greater_equal: [False  True  True]
Comparison-less: [ True False False]
Comparison-less_equal: [ True False  True]


In [24]:
#11)create an element-wise comparision(equal,equal within a tolerance) of two given arrays
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers:")
print(x)
print(y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
[  72   79   85   90  150 -135  120  -10   60  100]
[  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal:
[ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
True


In [30]:
#12create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array:
X = np.array([1, 7, 13, 105])
print("Original array:",X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array: [  1   7  13 105]
Size of the memory occupied by the said array:
16 bytes


In [33]:
#13) create an array of 10 zeros, 10 ones, 10 fives.
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [34]:
#14)create an array of the integers from 30 to 70
array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [35]:
#15)create a 3x3 identity matrix.
array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#16)NumPy program to generate a random number between 0 and 1.
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[0.90508624]


In [37]:
#17)program to generate an array of 15 random numbers from a standard normal distribution.
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[-0.19012888  0.43867262 -0.95151492  0.08469551  0.90530014  0.94031913
  2.85147295 -0.78484886 -0.20480037 -2.37904612  1.57713293  0.12404311
 -1.24574728  0.08100306 -0.86815316]


In [38]:
#18)create an array of all the even integers from 30 to 70
rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[ 0.99919566  0.16513555 -0.75049704  1.89322813 -2.74480042 -0.5770779
 -0.01569572 -0.17837313  1.07731026  1.06750834 -0.63870127 -0.53513214
  2.3466907   1.6868884   0.94846977]


In [39]:
#19)to generate an array of 15 random numbers from a standard normal distribution.
array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [40]:
#20)create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.
v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [41]:
#21) create a vector of length 10 with values ​​evenly distributed between 5 and 50.
v = np.linspace(10, 49, 5)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[10.   19.75 29.5  39.25 49.  ]


In [42]:
#22)create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [43]:
#23)create a vector of length 5 filled with arbitrary integers from 0 to 10.
x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[9 7 3 1 2]


In [44]:
#24)NumPy program to multiply the values ​​of two given vectors.
x = np.array([1, 8, 3, 5])
print("Vector-1")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)

Vector-1
[1 8 3 5]
Vector-2
[5 8 0 5]
Multiply the values of two said vectors:
[ 5 64  0 25]


In [45]:
#25)create a 3x4 matrix filled with values ​​from 10 to 21.
m= np.arange(10,22).reshape((3, 4))
print(m)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [46]:
#26)to find the number of rows and columns of a given matrix.
m= np.arange(10,22).reshape((3, 4))
print("Original matrix:")
print(m)
print("Number of rows and columns of the said matrix:")
print(m.shape)

Original matrix:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Number of rows and columns of the said matrix:
(3, 4)


In [47]:
#27)create a 3x3 identity matrix, i.e. diagonal elements are 1,the rest are 0.
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [49]:
#28)create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
x = np.ones((10, 10))
x[1:9, 1:9] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
#29)create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [51]:
#30)create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [52]:
#31)create a 3x3x3 array filled with arbitrary values.
x = np.random.random((3, 3, 3))
print(x)

[[[0.35221083 0.62599932 0.32171817]
  [0.19578616 0.19229731 0.70855332]
  [0.13671497 0.7713824  0.51284851]]

 [[0.01157359 0.88635538 0.88509723]
  [0.07158836 0.64490317 0.87621863]
  [0.2400548  0.25006007 0.18572366]]

 [[0.87881246 0.28018747 0.02300595]
  [0.88445293 0.91302619 0.16875253]
  [0.09071742 0.8830975  0.81945963]]]


In [53]:
#32)sum of all elements, sum of each column and sum of each row of a given array.
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [54]:
#33)program to compute the inner product of two given vectors.
x = np.array([4, 5])
y = np.array([7, 10])
print("Original vectors:")
print(x)
print(y)
print("Inner product of said vectors:")
print(np.dot(x, y))

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78


In [55]:
#34)NumPy program to add a vector to each row of a given matrix.
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)


Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


In [56]:
#35)NumPy program to save a given array to a binary file.
import numpy as np
import os
a = np.arange(20)
np.save('temp_arra.npy', a)
print("Check if 'temp_arra.npy' exists or not?")
if os.path.exists('temp_arra.npy'):
    x2 = np.load('temp_arra.npy')
    print(np.array_equal(a, x2))

Check if 'temp_arra.npy' exists or not?
True


In [1]:
#36)program to save two given arrays into a single file in compressed format (.npz format) and load it.
import numpy as np
import os
x = np.arange(10)
y = np.arange(11, 20)
print("Original arrays:")
print(x)
print(y)
np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

Original arrays:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [2]:
#37)program to save a given array to a text file and load it.
x = np.arange(12).reshape(4, 3)
print("Original array:")
print(x)
header = 'col1 col2 col3'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [6]:
#38)program to convert a given array into bytes, and load it as array.
a = np.array([1, 2, 3, 4, 5, 6])
print("Original array:")
print(a)
a_bytes = a.tobytes()
a2 = np.frombuffer(a_bytes, dtype=a.dtype)
print("After loading, content of the text file:")
print(a2)
print(np.array_equal(a, a2))

Original array:
[1 2 3 4 5 6]
After loading, content of the text file:
[1 2 3 4 5 6]
True


In [7]:
#39)program to convert a given list into an array, then again convert it into a list.
#Check initial list and final list are equal or not.
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)

True


In [8]:
#40) program to compute the x and y coordinates for points on a sine curve and plot the points using matplotlib.
import matplotlib.pyplot as plt
# Compute the x and y coordinates for points on a sine curve
x = np.arange(0, 3 * np.pi, 0.2)
y = np.sin(x)
print("Plot the points using matplotlib:")
plt.plot(x, y)
plt.show()

Plot the points using matplotlib:


<Figure size 640x480 with 1 Axes>

In [9]:
#41)program to convert numpy dtypes to native python types.
print("numpy.float32 to python float")
x = np.float32(0)
print(type(x))
pyval = x.item()
print(type(pyval))

numpy.float32 to python float
<class 'numpy.float32'>
<class 'float'>


In [10]:
#42)program to add elements in a matrix. If an element in the matrix is 0, we will not add the element below this element.
def sum_matrix_Elements(m):
    arra = np.array(m)   
    element_sum = 0  
    for p in range(len(arra)):  
        for q in range(len(arra[p])):  
            if arra[p][q] == 0 and p < len(arra)-1: 
                arra[p+1][q] = 0  
            element_sum += arra[p][q]  
    return element_sum
m = [[1, 1, 0, 2],
          [0, 3, 0, 3], 
          [1, 0, 4, 4]]
print("Original matrix:")
print(m)
print("Sum:")
print(sum_matrix_Elements(m))

Original matrix:
[[1, 1, 0, 2], [0, 3, 0, 3], [1, 0, 4, 4]]
Sum:
14


In [11]:
#43)NumPy program to find the missing data in a given array.
nums = np.array([[3, 2, np.nan, 1],
              [10, 12, 10, 9],
              [5, np.nan, 1, np.nan]])

print("Original array:") 
print(nums)
print("\nFind the missing data of the said array:")
print(np.isnan(nums))

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [12]:
#44)program to check whether two arrays are equal (element wise) or not.
nums1 = np.array([0.5, 1.5, 0.2])
nums2 = np.array([0.4999999999, 1.500000000, 0.2])
np.set_printoptions(precision=15)
print("Original arrays:")
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(nums1 == nums2)
nums1 = np.array([0.5, 1.5, 0.23])
nums2 = np.array([0.4999999999, 1.5000000001, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=15)
print(nums1)
print(nums2)
print("\nTest said two arrays are equal (element wise) or not:?")
print(np.equal(nums1, nums2))

Original arrays:
[0.5 1.5 0.2]
[0.4999999999 1.5          0.2         ]

Test said two arrays are equal (element wise) or not:?
[False  True  True]

Original arrays:
[0.5  1.5  0.23]
[0.4999999999 1.5000000001 0.23        ]

Test said two arrays are equal (element wise) or not:?
[False False  True]


In [7]:
#45)
import numpy as np
x=np.random.randint(100)
x

28