In [1]:
import numpy
a=numpy.array([1,5,3,8,7])
a

array([1, 5, 3, 8, 7])

In [3]:
import numpy as np
b=np.array(["a","d","g","s"])
b

array(['a', 'd', 'g', 's'], dtype='<U1')

In [4]:
import numpy as np
c=np.array(["a",1,"g",5])
c

array(['a', '1', 'g', '5'], dtype='<U1')

In [5]:
#checking NUMPY Version
np.__version__

'1.16.5'

In [6]:
#numpy object
type(a)

numpy.ndarray

In [7]:
#using tuple to create numpy array
arr=np.array((1,2,3,4,5))
arr

array([1, 2, 3, 4, 5])

In [8]:
#0 Dimension array
d=np.array(43)
d

array(43)

In [10]:
#1D Array
e=np.array([1,2,3])
e

array([1, 2, 3])

In [12]:
#2D Array
f=np.array([[1,2,3],[4,5,6]])
f

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#3D Array
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
g

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [20]:
#Checking no.of dimensions
d=np.array(43)
e=np.array([1,2,3])
f=np.array([[1,2,3],[4,5,6]])
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [21]:
d.ndim

0

In [17]:
e.ndim

1

In [18]:
f.ndim

2

In [19]:
g.ndim

3

In [23]:
#create array with n fixed dimensions:
e=np.array([1,2,3],ndmin=5)
print(e)
print("NO.Of dimensions:",e.ndim)

[[[[[1 2 3]]]]]
NO.Of dimensions: 5


In [25]:
#Getting element from 1D array
arr[1]

2

In [39]:
#Accessing elements from 2D Array
f[0]

array([1, 2, 3])

In [38]:
f[1,1]

5

In [44]:
#Accessing elements from 3D Array
#third element of second array of first array
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
g[0,1,2] #array of array, array ,element

6

In [29]:
#Getting and adding elements
arr[0]+arr[2]

4

In [3]:
#Negative indexing
import numpy as np
f=np.array([[1,2,3],[4,5,6]])
f[1,-1]

6

In [4]:
f[0,-2]

2

In [5]:
#Slicing 1D ARRAY
a=numpy.array([1,5,3,8,7])
a[0:3]

array([1, 5, 3])

In [6]:
a[1:]

array([5, 3, 8, 7])

In [7]:
a[:4]

array([1, 5, 3, 8])

In [12]:
a[-4:-1]

array([5, 3, 8])

In [13]:
a[-4:]

array([5, 3, 8, 7])

In [19]:
#start:end:step
a[0:4:2]

array([1, 3])

In [20]:
a[0::2]

array([1, 3, 7])

In [21]:
a[::2]

array([1, 3, 7])

In [22]:
#Slicing 2D ARRAY
f=np.array([[1,2,3],[4,5,6]])
f[0,0:2]

array([1, 2])

In [23]:
f[1,0:]

array([4, 5, 6])

In [24]:
#from both arrays access elements at a time
f[0:2,1]

array([2, 5])

In [25]:
f[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [26]:
f[0:2,0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#NUMPY DATA TYPES:
import numpy as np
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [28]:
arr=np.array(["Apple","Banana","Cherry"])
arr.dtype

dtype('<U6')

In [30]:
#Create array with data type string
arr=np.array([1,2,3,4,5],dtype='S')
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [31]:
arr.dtype

dtype('S1')

In [32]:
#creating array with data type 4 bytes integer
arr=np.array([1,2,3,4,5],dtype='i4')
arr

array([1, 2, 3, 4, 5])

In [33]:
arr.dtype

dtype('int32')

In [ ]:
#Converting data types:

In [35]:
#Changing float to int data types
arr=np.array([1.1,2.1,3.1,4.1,5.5])
newarr=arr.astype('i')
newarr

array([1, 2, 3, 4, 5], dtype=int32)

In [36]:
newarr.dtype

dtype('int32')

In [37]:
arr=np.array([1.1,2.1,3.1,4.1,5.5])
newarr=arr.astype(int)
newarr

array([1, 2, 3, 4, 5])

In [38]:
newarr.dtype

dtype('int32')

In [43]:
#Changing int to bool data type
arr=np.array([1,2,0,4,0])
newarr=arr.astype(bool)
newarr

array([ True,  True, False,  True, False])

In [44]:
#NUMPY COPY()
arr=np.array([1,2,0,4,0])
x=arr.copy()
x

array([1, 2, 0, 4, 0])

In [47]:
#NUMPY VIEW()
arr=np.array([1,2,0,4,0])
x=arr.view()
arr[0]=42
x

array([42,  2,  0,  4,  0])

In [48]:
arr

array([42,  2,  0,  4,  0])

In [51]:
#NUMPY BASE 
arr=np.array([1,2,0,4,0])
x=arr.copy()
y=arr.view()

In [52]:
x.base

In [50]:
y.base

array([1, 2, 0, 4, 0])

In [53]:
#NUMPY Shape
arr=np.array([1,2,0,4,0])
arr.shape

(5,)

In [55]:
f=np.array([[1,2,3],[4,5,6]])
f.shape

(2, 3)

In [56]:
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
g.shape

(2, 2, 3)

In [58]:
arr=np.array([1,2,0,4,0],ndmin=5)
arr.shape

(1, 1, 1, 1, 5)

In [60]:
arr=np.array([1,2,0,4,0,7,8,9,1])
newarr=arr.reshape(3,3)
newarr

array([[1, 2, 0],
       [4, 0, 7],
       [8, 9, 1]])

In [62]:
#RESHAPE
arr=np.array([1,2,0,4,0,7,8,9,1,9])
newarr=arr.reshape(2,5)
newarr

array([[1, 2, 0, 4, 0],
       [7, 8, 9, 1, 9]])

In [63]:
#Reshape 1D tO 3D
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [66]:
#Reshape 2D to 1D
f=np.array([[1,2,3],[4,5,6]])
newarr=f.reshape(-1)
newarr

array([1, 2, 3, 4, 5, 6])

In [67]:
#Reshape 3D t0 1D
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
newarr=g.reshape(-1)
newarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#ITERATING ELEMENTS

In [68]:
#FOR LOOP FOR 1D Array
import numpy
a=numpy.array([1,5,3,8,7])

for i in a:
    print(i)

1
5
3
8
7


In [69]:
#FOR LOOP FOR 2D Array
import numpy
f=np.array([[1,2,3],[4,5,6]])

for i in f:
    print(i)

[1 2 3]
[4 5 6]


In [70]:
#Printing every element in 2d array
import numpy
f=np.array([[1,2,3],[4,5,6]])

for i in f:
    for y in i:
        print(y)

1
2
3
4
5
6


In [71]:
#FOR LOOP FOR 2D Array
import numpy
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for i in g:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [72]:
#Printing every element in 3d array
import numpy
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for i in g:
    for y in i:
        for j in y:
            print(j)

1
2
3
4
5
6
7
8
9
10
11
12


In [73]:
#Printing every element in 3d array using ""nditer""
import numpy
g=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(g):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [77]:
#Printing every element in 3d array using ""nditer""
import numpy
g=np.array([[[1,2,3,10],[4,,15,5,6]])
for i in np.nditer(g[:,::2]):
    print(i)

SyntaxError: invalid syntax (<ipython-input-77-0177ef330892>, line 3)

In [79]:
#Concatenation of two 1D arrays
a=np.array([1,5,3,8,7])
b=np.array([1,2,3])
arr=np.concatenate((a,b))
arr

array([1, 5, 3, 8, 7, 1, 2, 3])

In [81]:
#Concatenation of two 2D arrays
f=np.array([[1,2,3],[4,5,6]])
g=np.array([[1,2,3],[4,5,6]])
arr=np.concatenate((f,g))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [87]:
#Concatenation of two 1D arrays using STACK FUNCTION
#error:All input must have the same shape 
a=np.array([1,5,3])
b=np.array([1,2,3])
arr=np.stack((a,b))
arr

array([[1, 5, 3],
       [1, 2, 3]])

In [86]:
a=np.array([1,5,3])
b=np.array([1,2,3])
arr=np.stack((a,b),axis=1)
arr

array([[1, 1],
       [5, 2],
       [3, 3]])

In [88]:
#Concatenation of two 1D arrays using HSTACK along rows
a=np.array([1,5,3])
b=np.array([1,2,3])
arr=np.hstack((a,b))
arr

array([1, 5, 3, 1, 2, 3])

In [89]:
#Concatenation of two 1D arrays using VSTACK along columns
a=np.array([1,5,3])
b=np.array([1,2,3])
arr=np.vstack((a,b))
arr

array([[1, 5, 3],
       [1, 2, 3]])

In [90]:
#Concatenation of two 1D arrays using dstack along depth
a=np.array([1,5,3])
b=np.array([1,2,3])
arr=np.dstack((a,b))
arr

array([[[1, 1],
        [5, 2],
        [3, 3]]])

In [5]:
#Split ARRAY:(np.array_split(array_name,parts_to_split))
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,3)#Split array into 3 parts
newarr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [6]:
newarr=np.array_split(arr,2)#Split array into 3 parts
newarr

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [7]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=np.array_split(arr,3)#Split array into 3 parts
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2 3]
[4 5 6]
[7 8]
